export type ApiResponse<T> = {
  success: boolean;
  data?: T;
  error?: string;
  meta?: any;
};

// Re-export specific enums or types if needed here, although typically UI will use types generated by Prisma client directly if possible.
